apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-reclamacion-vp
  namespace: foo
spec:
  storageClassName: ""
  volumeName: couchdb-pv 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi