apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-reclamacion-vp
  namespace: default
spec:
  storageClassName: ""
  volumeName: mi-volumen-persistente 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi